### PR TITLE
patch: Update dependencies & Fix creatorID issue

### PR DESCRIPTION
**Pull request by rahulkhatri137**

### CODE REVIEW

**Comment by Velosh** [comment]
I see that there are inconsistencies in the code. Btw, nice to meet you, can you fix it?

**Comment by rahulkhatri137** [comment]
> I see that there are inconsistencies in the code. Btw, nice to meet you, can you fix it?

I am not much active on GitHub for some reasons. I have hakalle as one of great projects. I will surely try to contribute to the project with the time.

**Comment by Velosh** [comment]
> I am not much active on GitHub for some reasons. I have hakalle as one of great projects. I will surely try to contribute to the project with the time.

I am no longer maintaining or updating this repository, but I can update it as normal if the user wants.

**Comment by Velosh** [comment]
Send me your GSI channel or anything that you've.

**Comment by rahulkhatri137** [comment]
Currently I don't have anything active but I am available with https://t.me/SGSI137

**Pull request merged**
